### ISSUE TITLE
Consider enabling CONFIG_SENSORS_RPI_POE_FAN

### ISSUE THREAD

**Issue by shdb** [sakaki-/bcmrpi3-kernel-bis#5]
It would be nice to have the POE HAT fan working.
The system gets quite hot without it.

**Comment by sakaki-** [comment]
Sounds sensible. If you submit a corresponding PR targetting `conform_config.sh`, I'll merge it (see e.g. #1 for an example)

**Comment by shdb** [comment]
OK perfect.
I made a pull request under #6 
Tanks for your great work bringing gentoo to the rpi.

**Comment by sakaki-** [comment]
[Appears to be in](https://github.com/sakaki-/bcmrpi3-kernel-bis/blob/1c841c3b340c59e37189f29c17b5f5ec1eb6b12f/vs_bcmrpi3_config.diff#L105-L107) the latest autobuild release. Please let me know if there are any issues; I don't have one of these devices to check if it works myself.
Best, sakaki

**Comment by shdb** [comment]
Thanks @sakaki- 
The module is in and it works like a charm. Now the temperature stays under 50°C. Before it was between 60 and 80°C.
